package cn.gfhnv.game.system.thinkingSystem;

public enum TagTypes {
    PREFER_HP, PREFER_ATK, PREFER_DEF, HP_RESTORATION, DEF_ENHANCE, HP_ENHANCE, ATK_ENHANCE, HP_LOSS, DEF_LOSS, ATK_LOSS, MANA_RESTORATION
}
